baseURL = ""
languageCode = "en-us"
title = "Trym Nohr Fjørtoft"
theme="cactus"


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "Publications"
url = "/posts"
weight = 3

[params]

  description = 'I am a PhD researcher at <a href="https://www.sv.uio.no/arena/english/people/aca/trymnf/index.html" target=_blank>ARENA Centre for European Studies</a>, University of Oslo. I’m currently working on the role and legitimacy of expertise in EU agencies.'

  showProjectsList = false

  dateFormat = "2006"
  dateFormatList = "1 January 2006"

  [[params.social]]
    name = "twitter"
    link = "http://twitter.com/trymnf"
  [[params.social]]
    name = "email"
    link = "trymnf@uio.no" 