baseURL = "https://www.trymnf.com/"
languageCode = "en-us"
title = "Trym Nohr Fjørtoft"
theme="cactus"


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


[params]

  description = 'I&apos;m a political scientist working on single-market governance, democracy and the legitimacy of unelected bodies, and migration and border control. I work as a postdoctoral fellow at <a href="https://www.sv.uio.no/arena/english/people/aca/trymnf/index.html" target=_blank>ARENA Centre for European Studies</a>, University of Oslo, where I&apos;m part of the <a href="https://www.sv.uio.no/arena/english/research/projects/singlemarkets/">SINGLEMARKETS</a> project.'

  showProjectsList = false
  
  logo-svg = true

  dateFormat = "2006"
  dateFormatList = "1 January 2006"
  dateFormatBlog = "2006-01-02"

  [[params.social]]
    name = "email"
    link = "trymnf@uio.no"
  [[params.social]]
    name = "twitter"
    link = "http://twitter.com/trymnf"
  [[params.social]]
    name = "bluesky"
    link = "https://bsky.app/profile/trymnf.bsky.social"  
  [[params.social]]
    name = "scholar"
    link = "https://scholar.google.com/citations?user=QzKZFhYAAAAJ"
  [[params.social]]
    name = "github"
    link = "https://github.com/trymnf"
